version: '3.8'

services:
  teste-web:
    image: nginx:alpine
    container_name: teste-github-proxmox
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    restart: always
